### ISSUE TITLE
Proprietary tools

### ISSUE THREAD

**Issue by authorisation** [asdfzxcvbn/pyzule#33]
Hello, I noticed that there are two seemingly proprietary tools being used for pyzule. Is the source code for  `install_name_tool` and `otool` available somewhere?

Thanks

**Comment by asdfzxcvbn** [comment]
hi,

`install_name_tool` and `otool` are two of apple's proprietary tools on macOS (part of xcode), so i believe you won't be able to find the source code anywhere. i'm not quite sure where the linux versions come from as i got them from azule.

**Comment by authorisation** [comment]
Ah alright I didn’t know that thanks
