### ISSUE TITLE
Add feature to fetch tweaks directly from repos

### ISSUE THREAD

**Issue by k3v1nwrld** [asdfzxcvbn/pyzule#34]
I remember azule had something like this and it was pretty useful for automating scripts without having to update the debs manually everytime they got an update. Idk if you would be interested in this since its quite a unique feature to ask for and many people may not use it.

**Comment by asdfzxcvbn** [comment]
honestly, if this is needed in an automated environment then you could just use api calls to do everything for you. it's a nice feature, but it would just add unnecessary bloat and checks that i don't want to add.
