### ISSUE TITLE
add flag to update pyzule

### ISSUE THREAD

**Issue by k3v1nwrld** [asdfzxcvbn/pyzule#35]
I think this is a must-have feature since there is no reason to be on an older version. I rarely check the repo for new commits and find myself always being behind on new features/fixes. If there is a reason to be on an older version, maybe adding a flag to not update it can be a solution. Thanks!

**Comment by asdfzxcvbn** [comment]
will consider adding versioning

imo automatic updates are never a good idea but i might be able to add a flag to manually update

**Comment by asdfzxcvbn** [comment]
added in 9708e12

**Comment by k3v1nwrld** [comment]
> added in 9708e12

Getting this error:
Traceback (most recent call last):
  File "/usr/local/bin/pyzule", line 18, in <module>
    from requests import get
ModuleNotFoundError: No module named 'requests'
