### ISSUE TITLE
Error when extracting debs on ios

### ISSUE THREAD

**Issue by k3v1nwrld** [asdfzxcvbn/pyzule#38]
Am getting the following error everytime I run pyzule on ios
`[*] extracting ipa..
[*] extracted ipa
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
Traceback (most recent call last):
  File "/var/jb/usr/local/bin/pyzule", line 337, in <module>
    run(f"tar -xf '{deb}' -C {output}", shell=True, executable="bash", check=True)
  File "/private/preboot/8CB08699AA0AEB1B91C6E222622B396D262FF60AE1201E5196D305F6B442FCEA205F713530DEB7A210AA70736460105B/dopamine-2sYsjh/procursus/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'tar -xf 'tweak.deb' -C .pyzule-1711402197.604955/0' returned non-zero exit status 2.`

**Comment by asdfzxcvbn** [comment]
but the same deb works fine on desktop?

**Comment by k3v1nwrld** [comment]
yep

**Comment by asdfzxcvbn** [comment]
are you sure? i dont think tar on iOS would have any reason to throw an invalid tar error, maybe verify via `sha256sum` ?

**Comment by k3v1nwrld** [comment]
I mean, I literally used sco to copy the files from my pc to my phone. i'll send a video later today

**Comment by k3v1nwrld** [comment]
Heres the one on my phone
![image](https://github.com/asdfzxcvbn/pyzule/assets/75213647/848bdaa1-da1c-489b-93f6-92018c09d08f)
And the same .deb on linux
![image](https://github.com/asdfzxcvbn/pyzule/assets/75213647/643f534d-7ec3-4ed9-bd4c-3a99b956727b)

**Comment by asdfzxcvbn** [comment]
strange.. i guess it's an issue with tar on iOS and not something i can fix from my side. as an alternative, you could extract the deb and make a .pyzule from it to use on your phone

**Comment by asdfzxcvbn** [comment]
scratch that, using ar will work.

**Comment by asdfzxcvbn** [comment]
can you try again?

**Comment by k3v1nwrld** [comment]
Just ran it again and it works with ar. Btw, are updates not supported on ios? Tried the --update flag but it didnt work, so i had to re-run the installation script manually

**Comment by asdfzxcvbn** [comment]
> Btw, are updates not supported on ios? Tried the --update flag but it didnt work, so i had to re-run the installation script manually

yeah, pretty much all 3rd party libs dont seem to work on iOS, so pyzule-ios relies purely on the stdlib

**Comment by k3v1nwrld** [comment]
Alr, thanks for the help
