### ISSUE TITLE
Need to fix Linux installation

### ISSUE THREAD

**Issue by d3ibis** [asdfzxcvbn/pyzule#39]
Brother, there is an issue while installing it on my server (Ubuntu)...

Keep giving syntax error, started from here:

> if (system := system()) == "Windows":
>     print("windows is not currently supported. install wsl and use pyzule there.")
>     sys.exit(1)

I deleted it & passed, then got another one in here:

> if not (args.o.endswith(".app") or args.o.endswith(".ipa")):
>     print("[?] file extension not specified, creating ipa")
>     args.o += ".ipa"
> if os.path.exists(args.o):
>     overwrite = input(f"[<] {args.o} already exists. overwrite? [Y/n] ").lower().strip()
>     if overwrite in ("y", "yes", ""):
>         del overwrite
>     else:
>         print("[>] quitting.")
>         sys.exit()
> EXTRACT_DIR = f".pyzule-{time()}"
> os.makedirs((REAL_EXTRACT_DIR := os.path.join(os.getcwd(), EXTRACT_DIR)))

for this one exactly:
> os.makedirs((REAL_EXTRACT_DIR := os.path.join(os.getcwd(), EXTRACT_DIR)))

All are giving errors, I'm having a totally new clean & installed setup on my server and ur pyzule is the 1st thing to install :D

**Comment by asdfzxcvbn** [comment]
you need a newer version of python. i believe v3.8 is the minimum.
