### ISSUE TITLE
not an issue but general question

### ISSUE THREAD

**Issue by xyz177** [asdfzxcvbn/pyzule#41]
1. How do I make .pyzule files?
2. How do I edit my .pyzule files?
3. What does .pyzule files do?

**Comment by asdfzxcvbn** [comment]
1. use [pyzule-gen](https://github.com/asdfzxcvbn/pyzule-gen)
2. you can't, you'd have to make a new one
3. they practically just "store" a pyzule command. think of this pyzule command:

`pyzule -i example.app -o test -uwsgf my.dylib`

you could use:

`pyzule-gen -o myConfig.pyzule -uwsgf my.dylib`

to generate a .pyzule file that stores your config including flags used, dylibs injected, changed icon, etc etc

then you could use it like so:

`pyzule -i example.app -o test -z myConfig.pyzule`

and it works just like the first command.

**Comment by xyz177** [comment]
oo got it
