### ISSUE TITLE
broken with swift apps 

### ISSUE THREAD

**Issue by nosexby** [asdfzxcvbn/pyzule#43]
python3 pyzule.py -i 5.ipa -o 1.ipa -f 1.deb
[*] extracting ipa..
[*] extracted ipa
[*] extracted 1.deb
[*] fixed dependency in tweak.dylib: /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate -> @rpath/CydiaSubstrate.framework/CydiaSubstrate
Traceback (most recent call last):
  File "/Users/user/Downloads/pyzule-main/pyzule.py", line 379, in <module>
    copytree(os.path.join(USER_DIR, real_dep_name), os.path.join(APP_PATH, inject_path, real_dep_name))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 558, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/zxcvbn/CydiaSubstrate.framework'
[*] deleting temporary directory..

**Comment by asdfzxcvbn** [comment]
are you running this from a github action?

**Comment by nosexby** [comment]
no im running from my server

**Comment by asdfzxcvbn** [comment]
yeah i see the issue, you cant clone the repo, use the install script

**Comment by nosexby** [comment]
I see it works with the script only problem is that I cant run the script on php as a command using shell_exec

**Comment by asdfzxcvbn** [comment]
> I see it works with the script only problem is that I cant run the script on php as a command using shell_exec

so the user dir is deleted or something? the install script is required because of dependencies that need to be downloaded, if you're planning on using pyzule in an environment like that then you'll have to modify either pyzule to do what you want or your script to download the dependencies somehow

**Comment by nosexby** [comment]
I fixed it thanks tho

**Comment by nosexby** [comment]
also great Job you guys should add a zsign just to sign apps bc the tweak injection doesn't work
