### ISSUE TITLE
Ellekit Support?

### ISSUE THREAD

**Issue by Mukul1127** [asdfzxcvbn/pyzule#44]
I did some research and it seems like adding ellekit is as simple as:
1. Adding a argument for it
2. Pretty much copying all of the Substitute Code but making it use `libellekit.dylib` instead of `libsubstitute.dylib`
3. Done (???)

I'll eventually get a pr made

**Comment by Mukul1127** [comment]
How nice of evelyneee to include CydiaSubstrate.framework in the ellekit deb

**Comment by asdfzxcvbn** [comment]
what are you talking about

ellekit is just a hooking library, it's a replacement for the CydiaSubstrate API

**Comment by asdfzxcvbn** [comment]
so there is pretty much no need for it

**Comment by Mukul1127** [comment]
Oh

**Comment by Mukul1127** [comment]
> what are you talking about
> 
> ellekit is just a hooking library, it's a replacement for the CydiaSubstrate API

So is substitute

**Comment by asdfzxcvbn** [comment]
> > what are you talking about
> > ellekit is just a hooking library, it's a replacement for the CydiaSubstrate API
> 
> Isn't substitute also a hooking library that is a replacement for the CydiaSubstrate API?

yeah, it's used in palera1n for example

it's just an alternative implementation
