### ISSUE TITLE
[Feature Request] -ext or -appex to inject .appex style extensions

### ISSUE THREAD

**Issue by yodaluca23** [asdfzxcvbn/pyzule#47]
Add a parameter could be somthing like -ext or -appex to inject .appex style extensions.
This should be easy to implement, it just needs to copy the .appex file to the Plugins folder if it exists, if not then make it and copy.

**Comment by asdfzxcvbn** [comment]
this is already supported..?

**Comment by yodaluca23** [comment]
> this is already supported..?

It is? How? Where?

**Comment by asdfzxcvbn** [comment]
> > this is already supported..?
> 
> It is? How? Where?

`-f files [files ...]  tweak files to inject into the ipa`

**Comment by yodaluca23** [comment]
> > > this is already supported..?
> > 
> > 
> > It is? How? Where?
> 
> `-f files [files ...] tweak files to inject into the ipa`

Oh... Mabye you should mention then what tweak files are supported...

**Comment by asdfzxcvbn** [comment]
> > > > this is already supported..?
> > > 
> > > 
> > > It is? How? Where?
> > 
> > 
> > `-f files [files ...] tweak files to inject into the ipa`
> 
> Oh... Mabye you should mention then what tweak files are supported...

https://github.com/asdfzxcvbn/pyzule/blob/d62050376bceece3e6f25082ed3d3b2a0cf9a597/README.md?plain=1#L10

🙂

**Comment by yodaluca23** [comment]
Thank you, sorry for wasting your time.
