### ISSUE TITLE
[Enhancement] Do not automatically fix dependencies if injecting them already or add option

### ISSUE THREAD

**Issue by yodaluca23** [asdfzxcvbn/pyzule#48]
I want to control what is injected into the .ipa, I may want to use old versions, may want to use altered versions, or just want to know exactly what is being used. Please check if the dependencies are being injected before trying to automatically fix dependencies or add an option to not automatically fix dependencies, maybe like "-Nfix".

**Comment by asdfzxcvbn** [comment]
i personally don't see a need for this.. you can temporarily replace the dependencies in `~/.config/pyzule` if needed

all the dependencies used for autofixing are straight from their original sources and unmodified

if dependencies are already injected, i believe pyzule wont overwrite them, instead it gives you a "warning" (?) that the dependency is already injected

this might be easy to add, however i won't take a PR for this

**Comment by yodaluca23** [comment]
> if dependencies are already injected, i believe pyzule wont overwrite them, instead it gives you a "warning" (?) that the dependency is already injected

Yea, bc right now it doesn't

``` pyzule -i "Build Components/OBFUSCATED.ipa" -o "Build Components/OBFUSCATED.ipa" -v OBFUSCATED -b OBFUSCATED -f "Build Components/OBFUSCATED.deb" "Build Components/OBFUSCATED.deb" "Build Components/OBFUSCATED.appex" "Build Components/dev.theos.orion14_1.0.1_iphoneos-arm.deb" "Build OBFUSCATED.deb" "Build Components/OBFUSCATED.deb" -u -w
[*] extracting ipa..
[*] extracted ipa
[*] extracted dev.theos.orion14_1.0.1_iphoneos-arm.deb
[*] extracted OBFUSCATED.deb
[*] extracted OBFUSCATED.deb
[*] extracted OBFUSCATED.deb
[*] extracted OBFUSCATED.deb
[*] fixed dependency in OBFUSCATED.dylib: /Library/Frameworks/Orion.framework/Orion -> @rpath/Orion.framework/Orion
[*] fixed dependency in OBFUSCATED.dylib: /Library/Frameworks/SwiftProtobuf.framework/SwiftProtobuf -> @rpath/SwiftProtobuf.framework/SwiftProtobuf
[*] fixed dependency in OBFUSCATED.dylib: /Library/Frameworks/Orion.framework/Orion -> @rpath/Orion.framework/Orion
[*] fixed dependency in OBFUSCATED.dylib: /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate -> @rpath/CydiaSubstrate.framework/CydiaSubstrate
[*] auto-injected CydiaSubstrate.framework
[*] auto-injected Orion.framework
[*] injected OBFUSCATED.dylib
[*] injected OBFUSCATED.dylib
[*] injected OBFUSCATED.dylib
[*] copied OBFUSCATED.bundle to app root
[*] injected OBFUSCATED.framework
[*] copied OBFUSCATED.appex to PlugIns
[*] restored app entitlements
[*] removed UISupportedDevices
[*] removed watch app
[*] changed app version to 2.1.4
[*] changed bundle id: OBFUSCATED -> OBFUSCATED
[*] changed all other bundle ids
[*] generating ipa using compression level 6..
[*] generated ipa at Build Components/OBFUSCATED.ipa
[*] deleting temporary directory..```

Notice it auto injects, Orion, then doesn't inject the Orion I supplied... None of "OBFUSCATED" is Orion.

**Comment by asdfzxcvbn** [comment]
no i mean if the ipa already contains the dependency

tbh, idk what happens if you inject your own deb of something that is supposed to be autofixed

pyzule's orion is from that exact deb you have anyway, and you can replace it in the directory i told you earlier

**Comment by yodaluca23** [comment]
Just btw, I added the "-Nfix" flag to my fork, just added an if statement for setting the dependency maps, it seems to work. Feel free to implement it if you change your mind.

https://github.com/yodaluca23/pyzule/blob/63b5623237c57e69ef34046ad68cf94992611f19/pyzule.py#L416
