### ISSUE TITLE
Change ALL bundle IDs.

### ISSUE THREAD

**Issue by yodaluca23** [asdfzxcvbn/pyzule#49]
When I use the change BundleID option, it seems as though some of the original is being retained, I can run View Entitlements on the app binary with Filza and I still see references to the original BundleID. I believe this is also what it breaking car play (and possibly others) support when changing the BundleID...

**Comment by asdfzxcvbn** [comment]
yeah the entitlements might reference the original bundle id and some other data

changing that in -b would already be too much of a hassle... well i admit it'd be quite easy but i dont think it's a huge problem

> I believe this is also what it breaking car play (and possibly others) support when changing the BundleID...

no that really shouldnt be an issue, the main executable's bundle id should just match the one from the appstore
